default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['db_host'] || '127.0.0.1' %>
  username: <%= ENV['db_user'] || 'postgres' %>
  password: <%= ENV['db_pass'] || 'postgres' %>

development:
  <<: *default
  database: global_educacional_development

test:
  <<: *default
  database: global_educacional_test

production:
  <<: *default
  database: <%= ENV['db_name'] || 'global_educacional_production' %>
  password: <%= ENV["GLOBAL_EDUCACIONAL_DATABASE_PASSWORD"] %>
