// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "vendor/jquery-3.6.0.min"
import "bootstrap.min"
import "isotope.pkgd.min"
import "imagesloaded.pkgd.min"
import "jquery.magnific-popup.min"
import "jquery.odometer.min"
import "jquery.appear"
import "tween-max.min"
import "select2.min"
import "slick.min"
import "slick-animation.min"
import "tg-cursor.min"
import "vivus.min"
import "ajax-form"
import "wow.min"
import "aos"
import "main"
    